baseURL = "http://localhost"
disablePathToLower = true
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "soho-master"
title = "A pé ou de carro"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 9
startLevel = 1
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[outputFormats.Atom]
baseName = "atom"
isHTML = false
isPlainText = false
mediaType = "application/atom+xml"
name = "Atom"
noUgly = true
permalinkable = false
rel = "alternate"
[outputFormats.outputs]
home = ["HTML", "ATOM"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML", "ATOM"]
[taxonomies]
author = "authors"
series = "series"
tag = "tags"
